import { ChakraProvider } from '@/Providers/chakra';
import type { Metadata } from 'next';
import { Roboto_Slab } from 'next/font/google';

const font = Roboto_Slab({ subsets: ['latin'], weight: ['400', '500'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
